#!/usr/bin/env ruby
require_relative '../lib/qrio'
$stdout.sync = true

filename = ARGV.shift || nil
if filename.nil?
  puts "Usage #{ $0 } filename"
  exit 1
end

qr = Qrio::Qr.load(filename)

qr.save_image(
  'debug.png',
  :crop => true,
  :annotate => [:matches, :finder_patterns, :angles,
    :alignment_patterns, :extracted_pixels]
)
